language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 8.3
      env: 'SCENARIO=symfony6 HIGHEST_LOWEST="update"'
    - php: 8.2
      env: 'SCENARIO=symfony6 HIGHEST_LOWEST="update"'
    - php: 8.1
      env: 'SCENARIO=symfony6 HIGHEST_LOWEST="update"'

sudo: false

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

install:
  - 'composer scenario "${SCENARIO}" "${HIGHEST_LOWEST-install}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v

